#include "DIO_CFG.h"
#include "..\MCAL\DIO_INT.h"
const DIO_status_t PinConfigratoin[TOTAL_PIN]={
	INFREE,/*PIND0*/
	INFREE,/*PIND1*/
	INPULL,/*PIND2*/
	INPULL,/*PIND3*/
	INPULL,/*PIND4*/
	INPULL,/*PIND5*/
	INFREE,/*PIND6*/
	INFREE,/*PIND7*/
	INFREE,/*PINC0*/
	INFREE,/*PINC1*/
	INFREE,/*PINC2*/
	INFREE,/*PINC3*/
	INFREE,/*PINC4*/
	INFREE,/*PINC5*/
	INFREE,/*PINC6*/
	INFREE,/*PINC7*/
	OUTPUT,/*PINB0*/
	OUTPUT,/*PINB1*/
	INPULL,/*PINB2*/
	INPULL,/*PINB3*/
	OUTPUT,/*PINB4*/
	OUTPUT,/*PINB5*/
	OUTPUT,/*PINB6*/
	OUTPUT,/*PINB7*/
	INFREE,/*PINA0*/
	OUTPUT,/*PINA1*/
	OUTPUT,/*PINA2*/
	OUTPUT,/*PINA3*/
	OUTPUT,/*PINA4*/
	OUTPUT,/*PINA5*/
	OUTPUT,/*PINA6*/
	INFREE /*PINA7*/
	
};